name: Bakeoff API Build Plan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Step 3 - Build with Maven
      run: mvn clean install -DskipTests
      
    - name: Webhook
      uses: distributhor/workflow-webhook
      with:
        url: "https://api.qoddi.com/push/?key=oj8etwqfalz5u647g93yhkmpcibvrdnxs12"
